### ISSUE TITLE
Support for Rawhide

### ISSUE THREAD

**Issue by ghost** [KyleGospo/gnome-vrr#1]
Hello!

I run rawhide on my system and I'm trying to figure out how to use your repo as a blueprint to make my own. I'm interested in maintaining a rawhide repo. Looking for ideas on how to start. Are you manually coping patches into this git repo from dor's?

Thanks for any help. Feel free to shoo me away. :)

**Comment by KyleGospo** [comment]
All the patches here are made by cherry picking commits from Dor's GitLab repos for Mutter and Gnome-Control-Center.

Gnome-Control-Center requires some rebasing currently as Dor's repo is a little behind, Mutter should cleanly patch though.

**Comment by ghost** [comment]
Thank you, Kyle!

**Comment by KyleGospo** [comment]
Closed as unplanned for the moment, the VRR patch set needs manual updating each time Mutter is updated which happens quite often on Rawhide.

**Comment by cyberphantom52** [comment]
[vrr.zip](https://github.com/KyleGospo/gnome-vrr/files/9733515/vrr.zip)
i have rebased the vrr patch for mutter on the lastest git, you can take a look if you want. @KyleGospo

**Comment by cyberphantom52** [comment]
@KyleGospo i have setup a copr here for testing purposes
https://copr.fedorainfracloud.org/coprs/cyberphantom/gnome-vrr/

It'd be really great if you decide to maintain F37 tho as i am usually buzy at work and can't find time to update these frequently.

**Comment by KyleGospo** [comment]
@cyberphantom52 Thank you for this patch, I've rebased it onto 43.1 and have begun supporting F37 in this repo.

**Comment by cyberphantom52** [comment]
> @cyberphantom52 Thank you for this patch, I've rebased it onto 43.1 and have begun supporting F37 in this repo.

Glad to help, i can close my copr now :)
