### ISSUE TITLE
Issue installing on brand new fedora 38 silverblue

### ISSUE THREAD

**Issue by lionblaze55** [KyleGospo/gnome-vrr#10]
`Resolving dependencies... done`
`Applying 4 overrides and 222 overlays`
`Processing packages... done`
`error: Checkout mutter-44.3.vrr.16-1.fc38.x86_64: Hardlinking 10/8ac100da7d75b7c4b74b8a0a3609b1ff8fadc82e66ff045aa652c749b9b9c1.file to org.gnome.mutter.gschema.xml: File exists
`
Have never had this issue while staging many hosts with the vrr patch, this particular hardware included. Any help would be appreciated!

**Comment by lionblaze55** [comment]
For further context, system is unmodified, fully updated, amd cpu and gpu.

**Comment by KyleGospo** [comment]
Upstream split Mutter into `mutter` and `mutter-common`, this should now be fixed. Be sure to check the updated install instructions on copr.
