### ISSUE TITLE
Gnome 45 support

### ISSUE THREAD

**Issue by trgeiger** [KyleGospo/gnome-vrr#11]
I just spent a bit rebasing and reworking the patch to work with mutter 45. The gnome-control-center bits worked fine with the same patch as before but mutter needed some finagling.

Since you need to make a new f39 branch I didn't open a PR for this.

Also Github doesn't let you upload .patch files I guess so it's just a .txt.
[myvrr_patch.txt](https://github.com/KyleGospo/gnome-vrr/files/12719641/myvrr_patch.txt)

**Comment by ghost** [comment]
Has the patch been tested yet? Now I will try to patch on ArchLinux, then, if successful, I will fork and add it to Fedora Copr

**Comment by trgeiger** [comment]
Yeah please test it out, I've just used it a bit yesterday. The changes needed to get it to compile weren't huge so I'm assuming nothing major has changed but I don't have a deep knowledge of how this all works. This is not not from the original PR author or anything, so I understand if Kyle wants to wait until there's a closer to upstream rebase.

**Comment by trgeiger** [comment]
Also, you will still need to add the experimental option `'variable-refresh-rate'` to gnome settings

**Comment by ghost** [comment]
The patch works more than successfully on ArchLinux. Now I am editing spec files and assembling them in copr. If successful, I will send a link here

**Comment by ghost** [comment]
Copy is already ready, the packages have been successfully assembled there: https://copr.fedorainfracloud.org/coprs/ar1son/gnome-vrr

**Comment by KyleGospo** [comment]
Thank you for this! The repo now includes support for the current F39 beta.
