### ISSUE TITLE
Updated for 45.5?

### ISSUE THREAD

**Issue by quidamphx** [KyleGospo/gnome-vrr#13]
Is there going to be a build for 45.5 until Fedora 40 releases with official support? I was using this (working great) on 45.4 but with a fresh install I can't download these packages as they're older than what I'm using.

Thanks.

**Comment by lionblaze55** [comment]
For what its worth, updating to fedora 40 beta was perfectly smooth and I have had no issues thus far, and VRR is working flawlessly.

**Comment by quidamphx** [comment]
I've been afraid to before release, just because I'm using an Asus G14 and
there were a lot of fixes and things I had to do to have it stable. I mean,
not a TON, but there's also a few extensions I use to solve problems that
haven't been updated yet too, so I'd have to wait or disable the version
checking and hope functionality isn't broken. With it being my main
machine, I prefer waiting for 40 to be released and get some initial fixes
otherwise I could end up in a worse spot.

That said, it's only a couple weeks away so I can wait if another build
isn't planned. I'm sure interim VRR support isn't high on the list for most
people right now

**Comment by quidamphx** [comment]
I ended up going ahead with the beta for 40.
