### ISSUE TITLE
Support for F37

### ISSUE THREAD

**Issue by nosajKenneth** [KyleGospo/gnome-vrr#2]
Seems we are waiting for gnome to still implement these fixes, for users trying out F37 Beta would love to be able to use your copr to install these patches.

**Comment by cyberphantom52** [comment]
I tried building mutter 43 with vrr patches but the build keeps failing due to patches not getting applied.

@KyleGospo any help?

**Comment by KyleGospo** [comment]
> I tried building mutter 43 with vrr patches but the build keeps failing due to patches not getting applied.
> 
> @KyleGospo any help?

What you're dealing with is exactly why I haven't offered Fedora 37 or Rawhide support yet. The patches need to be updated to the newer version of Mutter used in the beta, and that takes effort each time the VRR patch set is updated or Mutter is updated.

**Comment by KyleGospo** [comment]
Closed as unplanned for the moment, the VRR patch set needs manual updating each time Mutter is updated which happens quite often on a beta release of an operating system.

**Comment by KyleGospo** [comment]
Repo now offers Fedora 37 builds

**Comment by KyleGospo** [comment]
Repo now offers Fedora 37 builds
