### ISSUE TITLE
Upstream updates override the vrr packages (dnf priority fix)

### ISSUE THREAD

**Issue by SvdB-nonp** [KyleGospo/gnome-vrr#3]
Just a small issue, with a note on how to address it. Every time actual mutter or gnome-control-center has an update, VRR package is overwritten. Hence every update VRR breaks until the VRR repo is updated again.

This can be prevented by granting the VRR repo higher priority than the official repo. This is done by setting the `priority` option of the repository to `1`. This will grant the repo higher priority than the official (defaulting to priority 99 I think, so 98 should already work). All packages in the gnome-vrr repository (mutter, gnome-control-center) will now have higher priority, even if they are of a lower version.

```
sudo dnf config-manager --save --setopt="copr:copr.fedorainfracloud.org:kylegospo:gnome-vrr.priority=1"
```

As it is currently the case with the latest mutter update, I also tested this. Software center showed an update to the non-VRR mutter. However, after setting this priority, there is no update found anymore (as expected).

*Final note: I am not experienced with dnf that much. I just got annoyed by vrr breaking every time and this fixed it for me. So if there are downsides to this approach, I am not familiar with them.*

**Comment by KyleGospo** [comment]
Thank you, I've added this to the Copr repo's instructions for others to use. That brings Workstation & Silverblue into parity in this regard.
