### ISSUE TITLE
43.3: XWayland apps steal focus

### ISSUE THREAD

**Issue by marhkb** [KyleGospo/gnome-vrr#4]
XWayland apps steal focus Since 43.3. That makes working with other windows really hard as soon as an XWayland window has gotten the focus.

Upstream Bug
https://gitlab.gnome.org/GNOME/mutter/-/issues/2654

The upstream Fedora package includes a hotfix patch for this (0001-x11-Avoid-updating-focus-on-wayland-compositor.patch in https://kojipkgs.fedoraproject.org//packages/mutter/43.3/2.fc37/src/mutter-43.3-2.fc37.src.rpm) from the MR https://gitlab.gnome.org/GNOME/mutter/-/merge_requests/2841.

Could you also include this patch?

**Comment by KyleGospo** [comment]
Thank you for the report! This is now included as of `43.3.vrr.13-1`
