### ISSUE TITLE
CentOS stream COPR support

### ISSUE THREAD

**Issue by lionblaze55** [KyleGospo/gnome-vrr#6]
Hello! I use and appreciate this COPR heavily on fedora systems, and was wondering if there was a way to build the COPR against CentOS Stream as well. If an official maintained branch is out of scope I will attempt to do myself, though I must admit I am rather new to dealing with .rpms. Thanks in advance!

**Comment by KyleGospo** [comment]
Can you confirm what version of Mutter you're using on CentOS Stream? According to pkgs.org it's only on 40.9

If it's the same 44 as Fedora 38 I can just kick off Stream builds in the existing copr, any older and the best way to go would be a separate repo with older versions, which I'd be glad to assist you in setting up.

**Comment by lionblaze55** [comment]
It is 40.9. Would I have to go and find an old commit of the patch to build against this version of mutter?

**Comment by KyleGospo** [comment]
I believe the earliest version of the VRR patch is for 42, but I may be mistaken

**Comment by lionblaze55** [comment]
Seems so. Well thanks for your input anyways!
