### ISSUE TITLE
After installation, I can't switch to wayland

### ISSUE THREAD

**Issue by fisuri** [KyleGospo/gnome-vrr#8]
I use Wayland on Fedora 38, AMD RX6600

Installing:
mutter 44.3.vrr.15-1
gnome-control-center 44.3.vrr.4-1
xorg-x11-server-Xwayland	23.1.2-1

And wayland is forcibly replaced by Xorg. How to solve it?

**Comment by KyleGospo** [comment]
Please check the latest build, this should be resolved.

**Comment by fisuri** [comment]
Everything works, thanks for making the necessary changes to the build.
![Снимок экрана от 2023-08-07 12-52-30](https://github.com/KyleGospo/gnome-vrr/assets/37468176/9b66894a-db09-471c-bca9-d23abd73e746)
![Снимок экрана от 2023-08-07 12-52-34](https://github.com/KyleGospo/gnome-vrr/assets/37468176/eaf63997-3164-494c-bef1-c855b37a26a5)
